web:
  build: .
  command: 'bash -c ''npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user' # This overwrites the /app/user directory in the container with the files/folders in this projects directory
  links:
    - redis
redis:
  image: redis
  volumes:
    - ./redis/data:/data
